steps:
    - id: 'Build docker image'
      name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/$PROJECT_ID/pro-angular:$BUILD_ID", ".", "-f", "Dockerfile.stage"]
  
    - id: 'Push docker image'
      name: 'gcr.io/cloud-builders/docker'
      args: ["push",  "gcr.io/$PROJECT_ID/pro-angular:$BUILD_ID"]

    - id: 'Build json image'
    name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/pro-angular-jsonserver:$BUILD_ID", ".", "-f", "Dockerfile.jsonserver"]

    - id: 'Push json image'
    name: 'gcr.io/cloud-builders/docker'
    args: ["push",  "gcr.io/$PROJECT_ID/pro-angular-jsonserver:$BUILD_ID"]
  
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
      - 'run'
      - 'deploy'
      - 'pro-angular-run'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pro-angular:$BUILD_ID'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      
      - name: 'gcr.io/cloud-builders/gcloudjson'
      args:
      - 'run'
      - 'deploy'
      - 'pro-angular-jsonserver'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pro-angular-jsonserver:$BUILD_ID'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'