version: '3.3'

services:
    angularapp:
        build: .
        image: pro-angular-stage
        ports:
            - '80:80'

    jsonserver:
        image: json-server
        ports: 
            - '3000:3000'